# Generated by Django 3.1.2 on 2020-10-19 21:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('username', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('guests', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rsvp_url', models.CharField(max_length=300)),
                ('rsvp_alert', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('group_message', models.BooleanField()),
                ('group_ids', django.contrib.postgres.fields.jsonb.JSONField()),
                ('alert_type', models.CharField(max_length=50)),
                ('run_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=50)),
                ('group_name', models.CharField(max_length=50)),
                ('guests', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_address', models.CharField(max_length=50, null=True)),
                ('full_address', models.CharField(max_length=300, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('drive_distance', models.IntegerField()),
                ('rsvp_status', models.CharField(default='No Response', max_length=50)),
                ('number_of_guests', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='trial_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
    ]
