# Generated by Django 3.1.2 on 2020-10-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='group_ids',
            field=models.JSONField(),
        ),
    ]
