# Generated by Django 3.1.2 on 2020-10-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201019_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='guests',
            field=models.JSONField(),
        ),
    ]
