# Generated by Django 3.1.2 on 2020-10-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201019_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='accountData',
        ),
        migrations.RenameModel(
            old_name='alert',
            new_name='alertData',
        ),
        migrations.RenameModel(
            old_name='group',
            new_name='groupData',
        ),
        migrations.RenameModel(
            old_name='guest',
            new_name='guestData',
        ),
        migrations.RenameModel(
            old_name='trial_number',
            new_name='trialNumberData',
        ),
    ]
