# Generated by Django 3.1.3 on 2020-11-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201020_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='email_address',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='full_address',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
