# Generated by Django 3.1.3 on 2020-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201115_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
