# Generated by Django 3.1.3 on 2020-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201115_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='full_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
