# Generated by Django 3.1.3 on 2020-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201115_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='latitude',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='longitude',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
