# Generated by Django 3.1.3 on 2020-11-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201115_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='drive_distance',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='number_of_guests',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
