apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-messenger-api
spec:
  selector:
    matchLabels:
      app: wedding-messenger-api
  replicas: 1
  template:
    metadata:
      labels:
        app: wedding-messenger-api
    spec:
      containers:
      - name: wedding-messenger-api
        image: okteto.dev/wedding-messenger-api:latest
        ports:
        - containerPort: 8888
        env:
          account_sid: ${{ secrets.account_sid }}  
          auth_token: ${{ secrets.auth_token }}  
          db_password: ${{ secrets.db_password }}  