apiVersion: v1
kind: Service
metadata:
  name: wedding-messenger-api
spec:
  type: LoadBalancer 
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: wedding-messenger-api